### ISSUE TITLE
Importer seems to not update tilesheet images when re-importing.

### ISSUE THREAD

**Issue by radicaled** [vnen/godot-tiled-importer#35]
I made some pretty big edits to my tilesheet in order to use Tiled's awesome Terrain Tool. Mainly lots of moving tiles around in the `.png`.

However, it seems like the importer didn't re-import my tilesheet image -- so the map came out looking insane. I opened up the generated .scn file in Godot, and glanced through its Tilemaps, and it was obvious it was using an old (cached?) version of the the tilesheet.

Importing the `.tmx` file and saving it into a new scene works perfectly fine, though.

**Comment by radicaled** [comment]
I restarted Godot and the map suddenly started rendering fine!

Is this a bug in Godot? Or maybe the plugin isn't signaling to Godot that internal assets have been updated, so its not re-rendering the tilesets?

**Comment by vnen** [comment]
This is more related to how Godot handle resources than to this plugin. Are you embedding the images in the TileSet when importing?

TBH I think what's happening is that the editor is already using the resource and thus don't update to the newer version. So if you restart the editor (maybe only the scene) it'll work. I'll try to make some tests later.

**Comment by radicaled** [comment]
> Are you embedding the images in the TileSet when importing?

Yep. I'm storing my `.tmx` and `.tsx` and other assets in the project, so I don't want duplicate files I might accidentally edit hanging around, so I import everything as a single `.scn` file.

> TBH I think what's happening is that the editor is already using the resource and thus don't update to the newer version. So if you restart the editor (maybe only the scene) it'll work.

I believe I opened and closed the affected scene and nothing changed

**Comment by radicaled** [comment]
I can now reproduce this issue consistently. If my only changes to a Tiled map are adding "tile" objects to an object layer, Godot won't update the imported scene unless I open / close it or restart Godot.

Is this a known issue in Godot? Any issue # I can track against?

**Comment by vnen** [comment]
Godot won't update the open scene, you really need to close and reopen it. This will be fixed in Godot 3.0, as there'll be a way to reload the scene from the plugin.

**Comment by vnen** [comment]
This is solved on Godot 3, and there's nothing this plugin can do anyway, so I'll close this.

**Comment by gusg21** [comment]
Hi, sorry to reopen an old issue, but this appears to be still happening. Godot 3.2, Windows 10. Both the tileset and the tilemap don't update in other scenes unless I open the map scene.

**Comment by vnen** [comment]
As said, this is more of an issue with Godot, there's nothing that can be done from the plugin.
